### ISSUE TITLE
Genetics

### ISSUE THREAD

**Issue by johnWilshire** [johnWilshire/contests_model#5]
How are the trait values going to be passed from generation to generation?

ideally an algorithm for how to combine trait values of two individuals.

@wcornwell 
@daniel1noble 

also I have most of the 1 generational minimal model up in python. to run it, cd into the python directory  and run  `python simulation.py`

the contest algorithm so far is in nests.py
parameters are in parameters.json

**Comment by daniel1noble** [comment]
@johnWilshire and @wcornwell Thanks John. I'll have more of a think about this. Thanks for raising the issue. I will consult a few papers to have a look at and see if I can gets one code together quickly.

**Comment by wcornwell** [comment]
@daniel1noble we should check http://www.jstor.org/stable/pdf/40963463.pdf?acceptTC=true

**Comment by daniel1noble** [comment]
Got it @wcornwell! I'll have a look

**Comment by daniel1noble** [comment]
Got it @wcornwell! I'll have a look

**Comment by johnWilshire** [comment]
Their result that different sigma values for the perception of their quality determines the number of strategies is really cool.

Their way of doing the genetics in the first couple of pages should be fairly straight forward to implement, I will see if I can implement it today / tomorrow.

Very interesting read so far.
